#
###################################
# Site wide configuration
####################################
#
title:       "Alvaro's Blog"
description: "stuff"
url: http://alvarop.com

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       pygments
# excerpt_separator: <!--more-->
permalink:         /:year/:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Alvaro Prieto
  avatar: avatar.jpg
  job:
  bio: "..."
  email:
  disqus-shortname: alvarosblog
  twitter: alvaroprieto
  facebook:
  google:
    plus:
    analytics: UA-51324259-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alvarop
  linkedin: alvaroops
  youtube: apg88
  flickr: apg88
