- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Install Ruby
      apt: name={{ item }} state=latest
      with_items:
        - ruby2.0
        - ruby2.0-dev
    - name: install redcarpet
      apt: name=ruby-redcarpet state=present
    - name: Install jekyll
      script: /usr/bin/gem2.0 install jekyll
      become: yes
    - name: Install pygments.rb
      script: /usr/bin/gem2.0 install pygments.rb
      become: yes
